import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';

@Injectable()
export class InsightsService {
  constructor(private prisma: PrismaService) {}

  async getRepositorySummary(id: string, userId: string) {
    const repo = await this.prisma.repository.findFirst({
      where: { id, userId }
    });
    if (!repo) {
      throw new NotFoundException('Repository not found');
    }

    if (repo.summary) {
      return { summary: repo.summary };
    }

    const files = await this.prisma.repositoryFile.findMany({
      where: { repositoryId: id },
      select: { filePath: true, language: true, sizeBytes: true, lineCount: true },
      orderBy: { sizeBytes: 'desc' }
    });

    const readmeFile = await this.prisma.repositoryFile.findFirst({
      where: {
        repositoryId: id,
        filePath: {
          mode: 'insensitive',
          equals: 'readme.md'
        }
      },
      select: { content: true }
    });

    const packageJsonFile = await this.prisma.repositoryFile.findFirst({
      where: {
        repositoryId: id,
        filePath: {
          mode: 'insensitive',
          equals: 'package.json'
        }
      },
      select: { content: true }
    });

    const topFilesText = files
      .slice(0, 30)
      .map(f => `- ${f.filePath} (${f.language}, ${f.lineCount} lines)`)
      .join('\n');

    const systemPrompt = `You are a highly skilled software architect. Your goal is to analyze the codebase repository structure and details, and generate a clear, comprehensive summary and insight report for a developer.

Repository Name: ${repo.name}
Total Files: ${repo.fileCount}
Primary Language: ${repo.primaryLanguage || 'Unknown'}

Top Files in Repository:
${topFilesText}

${readmeFile?.content ? `Here is the README.md content:\n\`\`\`markdown\n${readmeFile.content.substring(0, 4000)}\n\`\`\`\n` : ''}
${packageJsonFile?.content ? `Here is the package.json content:\n\`\`\`json\n${packageJsonFile.content.substring(0, 2000)}\n\`\`\`\n` : ''}

Based on this information, generate a professional, retro-terminal styled analysis. Structure it with these sections:
1. **[SYSTEM_OVERVIEW]**: A 2-3 sentence high-level description of what the project is and what it accomplishes.
2. **[TECH_STACK]**: Bullet points of key languages, frameworks, main dependencies (especially from package.json), and databases used.
3. **[ARCHITECTURAL_BREAKDOWN]**: How the codebase is organized, explaining key directories and files.
4. **[DEVELOPMENT_INSIGHTS]**: 2-3 practical tips or notes for developers starting to work on this repository (e.g. entry points, structure patterns).

Format the entire output in clean Markdown. Keep the headers exactly like:
# SYSTEM_OVERVIEW
# TECH_STACK
# ARCHITECTURAL_BREAKDOWN
# DEVELOPMENT_INSIGHTS`;

    const apiKey = process.env.GEMINI_API_KEY || '';
    const chatModel = (process.env.GEMINI_CHAT_MODEL || 'gemini-1.5-flash').replace(/^"|"$/g, '');
    const modelName = chatModel.startsWith('models/') ? chatModel.substring(7) : chatModel;
    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

    let summaryText = '';
    try {
      const geminiRes = await fetch(geminiUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            role: 'user',
            parts: [{ text: systemPrompt }],
          }],
          generationConfig: {
            temperature: 0.2,
          },
        }),
      });

      if (!geminiRes.ok) {
        const errText = await geminiRes.text();
        throw new Error(`Gemini API returned ${geminiRes.status}: ${errText}`);
      }

      const resJson = await geminiRes.json();
      summaryText = resJson.candidates?.[0]?.content?.parts?.[0]?.text || '';
      if (!summaryText) {
        throw new Error('No summary text generated by Gemini.');
      }
    } catch (error: any) {
      summaryText = `### ERROR GENERATING SYSTEM INSIGHTS\nFailed to generate repository summary: ${error.message}`;
      return { summary: summaryText };
    }

    await this.prisma.repository.update({
      where: { id },
      data: { summary: summaryText }
    }).catch(err => console.error('Failed to save repo summary:', err));

    return { summary: summaryText };
  }
}
